updated return messages
Updated return messages. 

status: "success" || "failure"
error: (if failure)
info: (when success and data needs to be sent back)